site_name: Cil2bsb

theme:
    name: material
    favicon: images/logo-cil-2.png
    logo: images/logo-cil-2.png

nav:
    - Home: index.md
    - Apresentações:
        - Apresentação 01: 'Apresentacao/Apresentacao_1/apresentacao1.md'
        - Apresentação 02: ''
        - Apresentação 03: ''
        - Apresentação 04: ''
        - Apresentação 05: ''
        - Apresentação 06: ''
    - Planejamento: 
        - Planejamento: 'Planejamento/Planejamento.md'
        - Processo de Design: 'Planejamento/processo-de-design.md'

docs_dir: docs/
